kibana:
  image: kibana
  ports:
    - "5601:5601"
  links:
    - elasticsearch

elasticsearch:
  image: elasticsearch
  command: elasticsearch -Des.network.bind_host=0.0.0.0

topbeat:
  build: .
  links:
    - elasticsearch
